name: Modify Pull Request with Black Formatter

on:
  push:
    branches:
      - main

jobs:
  modify_pr:
    name: Modify Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Black formatter
        run: |
          pip install black
          black .

      - name: Modify Pull Request
        uses: peter-evans/modify-pull-request@v1
        with:
          add-labels: format
          commit-message: "Apply black formatter to code"
          branch: actions/black
