name: black-action
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linter_name:
    name: runner / black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check files using the black formatter
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: "."
      - name: Annotate diff changes using reviewdog
        if: steps.action_black.outputs.is_formatted == 'true'
        uses: reviewdog/action-checkstyle@v2
        with:
          name: blackfmt
          reporter: github-pr-check
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tool_args: --formatter black --diff "HEAD^"
