name: Format code

on:
  push:
    branches: [develop]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Format code with black
        run: |
          pip install black
          black .
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com
          git diff --quiet --exit-code || git add . && git commit -m "Format code with black" && git push
