name: Format code

on:
  push:
    branches: [ develop ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Format code with black
        run: |
          pip install black
          black .
          if [[ $(git diff --stat --exit-code) -ne 0 ]]; then
            git config user.name ${{ github.actor }}
            git config user.email ${{ github.actor }}@users.noreply.github.com
            git add .
            git commit -m "Format code with black"
            git push
          fi
