name: Format code

on:
  push:
    branches: [develop]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install black
        run: |
          pip install black
          black ./*.py
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com
          git diff --exit-code || (git add . && git commit -m "Format code with black" && git push)
          if [ $? -eq 0 ]; then
            echo "No changes to commit."
          else
            echo "Changes have been committed."
          fi
